# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

moveRightInC <- function(m) {
    .Call('BMLGrid_moveRightInC', PACKAGE = 'BMLGrid', m)
}

moveUpInC <- function(m) {
    .Call('BMLGrid_moveUpInC', PACKAGE = 'BMLGrid', m)
}

wrapRightInC <- function(m) {
    .Call('BMLGrid_wrapRightInC', PACKAGE = 'BMLGrid', m)
}

wrapUpInC <- function(m) {
    .Call('BMLGrid_wrapUpInC', PACKAGE = 'BMLGrid', m)
}

